
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int TBOOLEAN = 49;
  public static final int EQUALS = 36;
  public static final int STARTFUNC = 7;
  public static final int CLOSEPARENT = 10;
  public static final int PRG = 2;
  public static final int FOR = 26;
  public static final int MINUS = 33;
  public static final int WRITE = 17;
  public static final int STRINGCONST = 47;
  public static final int NOT = 45;
  public static final int TILDA = 44;
  public static final int AND = 42;
  public static final int SEMICOLON = 6;
  public static final int DOUBLEPOINTS = 13;
  public static final int OR = 43;
  public static final int INF = 38;
  public static final int INTEGERCONST = 50;
  public static final int COMMA = 11;
  public static final int ENDPRG = 4;
  public static final int ENDFOR = 29;
  public static final int PLUS = 32;
  public static final int IF = 19;
  public static final int ENDWHILE = 25;
  public static final int EOF = 0;
  public static final int SUPEQUAL = 41;
  public static final int STARTPRG = 3;
  public static final int RETURN = 18;
  public static final int EQUAL = 12;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int INFEQUAL = 39;
  public static final int ENDFUNC = 8;
  public static final int IDENT = 46;
  public static final int CONSTANT = 5;
  public static final int FROM = 27;
  public static final int TIMES = 34;
  public static final int ENDIF = 22;
  public static final int CLOSEBRACK = 15;
  public static final int ELSE = 21;
  public static final int TINTEGER = 48;
  public static final int READ = 16;
  public static final int TO = 28;
  public static final int WHILE = 23;
  public static final int OPENBRACK = 14;
  public static final int SUP = 40;
  public static final int THEN = 20;
  public static final int DIFF = 37;
  public static final int OPENPARENT = 9;
  public static final int FALSE = 31;
  public static final int DO = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRG",
  "STARTPRG",
  "ENDPRG",
  "CONSTANT",
  "SEMICOLON",
  "STARTFUNC",
  "ENDFUNC",
  "OPENPARENT",
  "CLOSEPARENT",
  "COMMA",
  "EQUAL",
  "DOUBLEPOINTS",
  "OPENBRACK",
  "CLOSEBRACK",
  "READ",
  "WRITE",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "FOR",
  "FROM",
  "TO",
  "ENDFOR",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQUALS",
  "DIFF",
  "INF",
  "INFEQUAL",
  "SUP",
  "SUPEQUAL",
  "AND",
  "OR",
  "TILDA",
  "NOT",
  "IDENT",
  "STRINGCONST",
  "TINTEGER",
  "TBOOLEAN",
  "INTEGERCONST"
  };
}

